version: '2'
services:
  xroad-soap-proxy:
    build: ./
    container_name: "xroad-soap-proxy"
    ports:
      - "5080:5080"
      - "5443:5443"
    environment:
      KEY: "${KEY}"
      CERT: "${CERT}"
    restart: always

volumes:
  sslcert: